-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

-- vim.api.nvim_create_autocmd("BufNewFile", {
--   print("This is cool"),
--   callback = function()
--     local file_name = vim.fn.input("Enter file name: ")
--     if file_name and file_name ~= "" then
--       vim.cmd("new " .. file_name)
--     end
--   end,
-- })
